implicit pattern
zhenglaizhang/github-scala pull request #21
Opened 2021-08-29 12:54 UTC by zhenglaizhang

2021-08-29 16:33 UTC, coding2world requested changes

2021-08-29 16:33 UTC, coding2world commented on util/src/test/scala/util/MathTest.scala
> +    squareRoot.isDefinedAt(-1)
add assert ?

2021-08-30 11:29 UTC, zhenglaizhang commented on util/src/test/scala/util/MathTest.scala
> +    squareRoot.isDefinedAt(-1)
sure, will do

2021-08-31 00:31 UTC, zhenglaizhang commented on util/src/test/scala/util/MathTest.scala
> +    squareRoot.isDefinedAt(-1)
done

2021-08-31 11:35 UTC, zhenglaizhang commented
@coding2world let me merge this again, so that I can kick off next commits

2021-08-31 11:35 UTC, merged